config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save 
      flash[:success] = "Kitten created!"
      redirect_to root_url
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update_attributes(kitten_params)
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    if @kitten.destroy
      flash[:success] = 'Kitten deleted (you murderer)'
      redirect_to root_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to @kitten
    end
  end
  

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= simple_form_for @kitten do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :cuteness %>
  <%= f.input :softness %>
  <%= f.button :submit %>
<% end %>

app/views/kittens/edit.html.erb
<%= render 'form' %>
<%= link_to "delete", @kitten, method: :delete, data: { confirm: "You wanna delete this little fluffy thing?" } %>

app/views/kittens/index.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<%= link_to "New Kitten", new_kitten_path %>
<% @kittens.each_with_index do |kitten, i| %>
  <p>Kitten: <%= i + 1 %>
  <p>Name: <%= kitten.name %></p>
  <p>Age: <%= kitten.age %></p>
  <p>Softness Degree: <%= kitten.softness %></p>
  <p>Cuteness Degree: <%= kitten.cuteness %> </p>
  <%= link_to "edit", edit_kitten_path(kitten) %>
  <%= link_to "delete", kitten, method: :delete, data: { confirm: "You wanna delete this little fluffy thing?" } %>
  <hr>
<% end %>

app/views/kittens/new.html.erb
<%= render 'form' %>

app/views/kittens/show.html.erb
<p>Kitten: <%= @kitten.id %>
<p>Name: <%= @kitten.name %></p>
<p>Age: <%= @kitten.age %></p>
<p>Softness Degree: <%= @kitten.softness %></p>
<p>Cuteness Degree: <%= @kitten.cuteness %> </p>
<%= link_to "delete", @kitten, method: :delete, data: { confirm: "You wanna delete this little fluffy thing?" } %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>